services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-news_api}
    volumes:
      - ${POSTGRES_VOLUME:-./postgres/data}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ${PG_ADMIN_VOLUME:-./pgadmin}:/var/lib/pgadmin
    ports:
      - "${PG_ADMIN_PORT:-5050}:80"
    networks:
      - postgres-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
